### ISSUE TITLE
Adding Vows or Progress throws vue error in console

### ISSUE THREAD

**Issue by tagnullde** [ben/foundry-ironsworn#186]
Adding works, but those errors show up in the console. Might be worth a look?

![image](https://user-images.githubusercontent.com/44159008/153703562-fce3b501-a208-4f7c-94bd-cb895e89c31b.png)

Regards
x41

**Comment by ben** [comment]
Ooh, nice find. I'll fix these warnings in #187.

**Comment by tagnullde** [comment]
Thanks for looking into it. The fix doesn't seem to fix it though. 
Just updated and tested again. I added a bonus CSS Error at startup, but I think it's related to Issue #185.  

![image](https://user-images.githubusercontent.com/44159008/153718377-5cf30c04-6663-4ab6-b117-82f5a8cc37da.png)

Version:

vue version 1.1

![image](https://user-images.githubusercontent.com/44159008/153718492-abf0e60b-932e-4c06-944e-6d58f62c8d82.png)

**Comment by ben** [comment]
Ah okay. I'm running a local dev proxy, which for some reason doesn't surface these errors. I think I've tracked it down.

**Comment by ben** [comment]
#186 should fix this warning. I'm glad it's not stopping gameplay.

**Comment by tagnullde** [comment]
Sort of. The "World Truths" dialog pops up now. And the CSS Error is gone. But adding vows still throw errors, new ones though.
Maybe something is wrong with the Char-Sheet? The changelog mentions some new "notes" tab, and I have no tabs in my charsheet.

![image](https://user-images.githubusercontent.com/44159008/153723649-6879aad4-7eb3-42c5-ace8-1a9855e9e10f.png)

**Comment by ben** [comment]
That's referring to the Starforged character sheet, which is behind a system setting. There have been some system-wide changes made there.

Fortunately these are just warnings, and aren't preventing you from doing anything afaict. I'll reopen this and aim to fix them with another patch. They snuck by because they don't show up when I'm running my development setup.

**Comment by tagnullde** [comment]
That's fine with me. Thanks for the effort. :)
